name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TIMESTAMP: $((date +%s))

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t eviloma-family-bot:${TIMESTAMP} -t eviloma-family-bot:latest -f Dockerfile .

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the Docker image with "latest" tag to Docker Hub
      run: docker push eviloma-family-bot:latest

    - name: Push the Docker image with version-specific tag to Docker Hub
      run: docker push eviloma-family-bot:${TIMESTAMP}
