name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag eviloma-family-bot:$(date +%s)

    - name: Tag the Docker image as "latest"
      run: docker tag eviloma-family-bot:$(date +%s) eviloma-family-bot:latest

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the Docker image with "latest" tag to Docker Hub
      run: docker push eviloma-family-bot:latest

    - name: Push the Docker image with version-specific tag to Docker Hub
      run: docker push eviloma-family-bot:$(date +%s)
